name = "HyperActiveLearning"
uuid = "bbe0bd0f-45a1-453e-8b96-d2608abdd39e"
authors = ["Christoph Ortner <christophortner0@gmail.com> and contributors (please add your names)"]
version = "0.0.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
